appserver:
  name: appserver
  image:
    name: appserver
    tag: v1
    exposedPort: 8080
    healthCheck:
      ping: /api/v1/healths/ping
      failureTimes: 5
  replicas: 3
  env:
    NODE_END: local
  service:
    type: ClusterIP

nginx:
  name: nginx
  image:
    name: nginx
    tag: v1
    exposedPort: 80
  replicas: 1
  service:
    type: LoadBalancer
